version: "3.8"
services:
  api:
    build: ./api
    ports:
      - "4000:4000"
    env_file:
      - .env
    depends_on:
      - mysql
      - redis
    volumes:
      - ./api:/app

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: dub
      MYSQL_USER: dub
      MYSQL_PASSWORD: dubpassword
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  mysql-data:

